version: '3'
services: 
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes: 
      - ./api/api:/app/api
      - ./api/package.json:/app/package.json
    #ports: 
    #  - "3001:3001"
  site:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./archivos-calc-super
    volumes: 
      - ./archivos-calc-super/public:/app/public
      - ./archivos-calc-super/src:/app/src
      - ./archivos-calc-super/views:/app/views
      - ./archivos-calc-super/package.json:/app/package.json
    #ports: 
    #  - "80:3000"
  nginx:
    depends_on: 
      - site
      - api
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./NGINX
    ports: 
      - "8080:80"