version: '3'
services: 
  redis:
    image: 'redis:latest'
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    volumes: 
      - ./worker/routes:/app/routes
      - ./worker/package.json:/app/package.json
    expose: 
      - "4002"
    environment:
      - TOKEN_VALUE=julioTOken
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    environment:
      - TOKEN_VALUE=julioTOken
    
  site:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./archivos-calc-super
    volumes: 
      - ./archivos-calc-super/public:/app/public
      - ./archivos-calc-super/src:/app/src
      - ./archivos-calc-super/views:/app/views
      - ./archivos-calc-super/package.json:/app/package.json
    #ports: 
    #  - "80:3000"
  nginx:
    depends_on: 
      - site
      - api
      - worker
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./NGINX
    ports: 
      - "80:80"

    